version: '3'

services:

  nginx:
    build: ./nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

  app: 
    build:
      context: node 
    container_name: app
    networks:
      - node-network
    command: sh -c "npm install && node index.js"
    volumes:
      - ./node:/usr/src/app
      # - /usr/src/app/node_modules # volume anonimo (link simbolico)
    tty: true 
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7.16
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3

  
  
networks:
  node-network:
    driver: bridge